package signavio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Prospect")
   private signavio.Prospect prospect;
   @org.kie.api.definition.type.Label(value = "Offer")
   private signavio.Offer offer;
   @org.kie.api.definition.type.Label(value = "Rejection")
   private signavio.Rejection rejection;

   public Message()
   {
   }

   public signavio.Prospect getProspect()
   {
      return this.prospect;
   }

   public void setProspect(signavio.Prospect prospect)
   {
      this.prospect = prospect;
   }

   public signavio.Offer getOffer()
   {
      return this.offer;
   }

   public void setOffer(signavio.Offer offer)
   {
      this.offer = offer;
   }

   public signavio.Rejection getRejection()
   {
      return this.rejection;
   }

   public void setRejection(signavio.Rejection rejection)
   {
      this.rejection = rejection;
   }

   public Message(signavio.Prospect prospect, signavio.Offer offer,
         signavio.Rejection rejection)
   {
      this.prospect = prospect;
      this.offer = offer;
      this.rejection = rejection;
   }

}