package signavio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Offer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Offer Number")
   private java.lang.Long offerNumber;
   @org.kie.api.definition.type.Label("Card Type")
   private java.lang.String cardType;
   @org.kie.api.definition.type.Label("Interest Rate")
   private java.lang.Double interestRate;
   @org.kie.api.definition.type.Label("Maximum Credit")
   private java.lang.Double maxCredit;

   @org.kie.api.definition.type.Label("Comment")
   private java.lang.String comment;

   @org.kie.api.definition.type.Label(value = "Prospect")
   private signavio.Prospect prospect;

   public Offer()
   {
   }

   public java.lang.Long getOfferNumber()
   {
      return this.offerNumber;
   }

   public void setOfferNumber(java.lang.Long offerNumber)
   {
      this.offerNumber = offerNumber;
   }

   public java.lang.String getCardType()
   {
      return this.cardType;
   }

   public void setCardType(java.lang.String cardType)
   {
      this.cardType = cardType;
   }

   public java.lang.Double getInterestRate()
   {
      return this.interestRate;
   }

   public void setInterestRate(java.lang.Double interestRate)
   {
      this.interestRate = interestRate;
   }

   public java.lang.Double getMaxCredit()
   {
      return this.maxCredit;
   }

   public void setMaxCredit(java.lang.Double maxCredit)
   {
      this.maxCredit = maxCredit;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public signavio.Prospect getProspect()
   {
      return this.prospect;
   }

   public void setProspect(signavio.Prospect prospect)
   {
      this.prospect = prospect;
   }

   public Offer(java.lang.Long offerNumber, java.lang.String cardType,
         java.lang.Double interestRate, java.lang.Double maxCredit,
         java.lang.String comment, signavio.Prospect prospect)
   {
      this.offerNumber = offerNumber;
      this.cardType = cardType;
      this.interestRate = interestRate;
      this.maxCredit = maxCredit;
      this.comment = comment;
      this.prospect = prospect;
   }
   
    public String toString() {
       StringBuilder builder = new StringBuilder("Offer: ");
       builder.append("offerNumber: ").append(offerNumber).append(", cardType: ").append(cardType).append(", interestRate: ").append(interestRate).append(", maxCredit: ").append(maxCredit).append(", comment: ").append(comment).append(", prospect: ").append(prospect);
       return builder.toString();
   }

}