package signavio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Offer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Offer Number")
   private java.lang.Long offerNumber;
   @org.kie.api.definition.type.Label(value = "Card Type")
   private java.lang.String cardType;
   @org.kie.api.definition.type.Label(value = "Interest Rate")
   private java.lang.Double interestRate;
   @org.kie.api.definition.type.Label(value = "Maximum Credit")
   private java.lang.Double maxCredit;

   public Offer()
   {
   }

   public java.lang.Long getOfferNumber()
   {
      return this.offerNumber;
   }

   public void setOfferNumber(java.lang.Long offerNumber)
   {
      this.offerNumber = offerNumber;
   }

   public java.lang.String getCardType()
   {
      return this.cardType;
   }

   public void setCardType(java.lang.String cardType)
   {
      this.cardType = cardType;
   }

   public java.lang.Double getInterestRate()
   {
      return this.interestRate;
   }

   public void setInterestRate(java.lang.Double interestRate)
   {
      this.interestRate = interestRate;
   }

   public java.lang.Double getMaxCredit()
   {
      return this.maxCredit;
   }

   public void setMaxCredit(java.lang.Double maxCredit)
   {
      this.maxCredit = maxCredit;
   }

   public Offer(java.lang.Long offerNumber, java.lang.String cardType,
         java.lang.Double interestRate, java.lang.Double maxCredit)
   {
      this.offerNumber = offerNumber;
      this.cardType = cardType;
      this.interestRate = interestRate;
      this.maxCredit = maxCredit;
   }

}