package signavio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prospect implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Social Security Number")
   private java.lang.String ssn;
   @org.kie.api.definition.type.Label(value = "E-mail address")
   private java.lang.String email;

   public Prospect()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.String ssn)
   {
      this.ssn = ssn;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public Prospect(java.lang.String name, java.lang.String ssn,
         java.lang.String email)
   {
      this.name = name;
      this.ssn = ssn;
      this.email = email;
   }
   
   public void toString() {
       StringBuilder builder = new StringBuilder("Prospect: ");
       builder.append("name: ").append(name).append(", ssn: ").append(ssn).append(", email: ").append(email);
       return builder.toString();
   }

}