package signavio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rejection implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "String")
   private java.lang.String reason;
   @org.kie.api.definition.type.Label(value = "Prospect")
   private signavio.Prospect prospect;

   public Rejection()
   {
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public signavio.Prospect getProspect()
   {
      return this.prospect;
   }

   public void setProspect(signavio.Prospect prospect)
   {
      this.prospect = prospect;
   }

   public Rejection(java.lang.String reason, signavio.Prospect prospect)
   {
      this.reason = reason;
      this.prospect = prospect;
   }
   
   public String toString() {
       StringBuilder builder = new StringBuilder("Rejection: ");
       builder.append("reason: ").append(reason).append(", prospect: ").append(prospect);
       return builder.toString();
   }

}